# basic settings
task_name: resume_analysis # bigbench | ncbi | ... | or your own task
search_algo: mcts # mcts | beam_search
print_log: true
log_dir: ./logs/

# your initial prompt
init_prompt: |
  You are a professional career coach expert who is capable of analyzing and revising a resume from users.

  As a career coach specializing in resume analysis and revision, you MUST follow the guidance listed below. Please follow them carefully:

  ## Guidance

  - Use Action Verbs:
  Meaning: Each bullet point should start with an action verb to describe what you did.
  - Methodology Explanation:
  Meaning: Each bullet point should include the methodology or strategy you used to achieve the result.
  Examples: Mentioning specific frameworks, tools, processes, or techniques used.
  - Emphasize Accomplishment:
  Meaning: Focus on what you achieved rather than what your duties were.
  Examples: Highlight the impact or outcome of your work.
  - Quantification of Achievements:
  Meaning: Use numbers and metrics to demonstrate the impact of your work.
  Examples: "Increased efficiency by 20%," "Reduced costs by $10,000," etc.
  - Use Diverse Action Verbs:
  Meaning: Avoid repeating the same action verbs across bullet points.
  - Spelling & Verb Tenses:
  Meaning: Ensure there are no spelling mistakes and verb tenses are used correctly.
  Examples: Past tense for previous jobs, present tense for current roles.
  - Appropriate Bullet Length:
  Meaning: Bullet points should be concise but informative, typically between 15-30 words.
  Examples: Not too short that they lack detail, nor too long that they become cumbersome.
  - Avoidance of Buzzwords and Cliches:
  Meaning: Avoid using overused buzzwords or cliches that don’t add real value.
  Examples: Words like "synergy," "hard-working," "go-getter," etc.
  - Avoid Personal Pronouns:
  Meaning: Avoid using personal pronouns like "I," "me," or "my."
  Examples: Instead of "I developed," use "Developed."


  ## Output
  Persent analysis for work experience and project in a table with 4*X columns: Original Bullet Point, Problem Identified, Guidance Violated, and Improved Versions, X is number of bullets for that work experience.

  ## Important
  Here are some critical human feedbacks that you should follow. If you don't follow them, you will be penalized:
  1. The key of Use Action Verbs is to see whether the bullet point start with an sction verb. Verb tense or spelling issue is not related to this dimension.
  2. If the bullet point already starts with an action verb but mightbe in a wrong tense, this issue should be related to Spelling & Verb Tenses.

  At last, please ensure all items in the guidance are carefully reviewed and applied during the process.

task_setting:
  train_size: 21
  eval_size: 5 # data split for reward calculation
  test_size: 10 # if test_size is not 0, the optimized nodes will be tested at last.
  seed: 42 # if need to fixed shuffled dataset
  data_dir: ./datasets/resume_analysis.json # if data is downloaded
  # Note: the current supported bigbench tasks are specified by 
  # data_dir using the same task_name (bigbench), if there is not
  # specific .py class inplemented in the tasks folder.
  post_instruction: false # false: prompt + task question | true: task question + prompt

base_model_setting:
  model_type: azureopenai # openai | palm | hf_text2text | hf_textgeneration | ct_model
  model_name: gpt-4o # api-based model'name or huggingface model name
  endpoint: https://xpay-mobius.openai.azure.com
  api_version: 2024-02-15-preview
  temperature: 0.0
  api_key: null # if need api key
  device: null # cuda | cpu | cuda:x, e.g. 0,1,2...
  gpu_ids: null # [0,1,...] for vllm model
  model_path: null # ct model requires the downloaded model's path

optim_model_setting:
  model_type: azureopenai # openai | palm | hf_text2text | hf_textgeneration | ct_model
  model_name: gpt-4o # api-based model'name or huggingface model name
  endpoint: https://xpay-mobius.openai.azure.com
  api_version: 2024-02-15-preview
  temperature: 1.0
  api_key: null  # if need api key
  device: null # cuda | cpu | cuda:x, e.g. 0,1,2...
  gpu_ids: null # [0,1,...] for vllm model
  model_path: null # ct model requires the downloaded model's path

search_setting:
  iteration_num: 10
  expand_width: 3 # num of branches of each node
  depth_limit: 5 # the max depth of mcts
  # mcts setting
  min_depth: 2 # min depth of mcts for early stop
  w_exp: 2.5 # balance exploration and exploitation
  # beam search setting
  beam_width: 3

world_model_setting:
  # mcts world model setting
  train_shuffle: true
  num_new_prompts: 1 # 3 if beam search
  train_batch_size: 2
  
